name = "All the Mods 9"
author = "ATMTeam"
version = "0.2.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07fde1e581dc65dd449acd82ab9a54576f117134baf66752e47f12830c1b8d90"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
