name = "All the Mods 9"
author = "ATMTeam"
version = "0.2.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0993b0f1c273a132eebce9b37c19b9bb41d562f8dd1a3541e84542290544f762"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
