name = "All the Mods 9"
author = "ATMTeam"
version = "0.2.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e822852765a167ea86b3fdb68b6f4090b635fe527b12846ec447cce5c4accb2d"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
