name = "All the Mods 9"
author = "ATMTeam"
version = "0.2.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e08f0429343cebcb9abaedef384b3b02127feb3f4cdc04c8a467bf4e2799a368"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
